In [1]:
# STEP 1: Upload the ZIP File
from google.colab import files
uploaded = files.upload()

Saving archive (3).zip to archive (3).zip

In [30]:
# STEP 2: Extract the ZIP File
import zipfile

zip_file_name = "archive (3).zip"

with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall()

print("Extraction completed!")

Extraction completed!

In [31]:
# STEP 3: Check What File Got Extracted
import os
os.listdir()

['.config',
 'archive (3).zip',
 'netflix_titles.csv.csv',
 'netflix_cleaned.csv',
 'sample_data']

In [32]:
# STEP 4: Import Pandas and Read the Dataset
import pandas as pd

df = pd.read_csv("netflix_titles.csv.csv")

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [33]:
# STEP 5: Basic Structure Analysis
df.shape

# Column Names:
print("Column Names: ")
df.columns
print()

# Data Types
print("Data Types: ")
df.info()

Column Names:

Data Types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [34]:
# STEP 6: Check Missing Values Properly
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [35]:
# STEP 7: Handle Missing Values

# director column (2634 missing)
df['director'] = df['director'].fillna("Unknown")
# Now verify director column again:
df['director'].isnull().sum()



# cast (825 missing) column:
df['cast'] = df['cast'].fillna("Not Available")
#  Now verify cast column again:
df['cast'].isnull().sum()



# country (831 missing) column:
df['country'] = df['country'].fillna("Unknown")
#  Now verify country column again:
df['country'].isnull().sum()

np.int64(0)

In [36]:
# director, cast, and country columns should show zero
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64

In [37]:
# rating (4 missing) column:
# Very small number. We can fill with most frequent rating (mode).
df['rating'].mode()

0    TV-MA
Name: rating, dtype: object

In [38]:
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

In [39]:
# now rating also shows zero
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           0
duration         3
listed_in        0
description      0
dtype: int64

In [40]:
# duration (3 missing) column:
# Only 3 rows.Best option: Drop those rows.
df = df.dropna(subset=['duration'])

# Check shape again:
df.shape # now it should show only 8804 rows earlier 8807 rows.

(8804, 12)

In [41]:
# date_added (10 missing) column:
# We can drop them since very few.
df = df.dropna(subset=['date_added'])

# Check shape again:
df.shape

(8794, 12)

In [42]:
# Final Verification
df.isnull().sum() # there should not be any null values now.. everyhting should be zero..

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [43]:
# STEP 8: Check for Duplicate Records
df.duplicated().sum()

np.int64(0)

In [44]:
# STEP 9: Standardize Text Columns

# Remove Extra Spaces from All Object Columns
# Select all object (string) columns
string_columns = df.select_dtypes(include='object').columns

# Remove leading and trailing spaces
for col in string_columns:
    df[col] = df[col].str.strip()



# Standardize Column Names
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [45]:
# STEP 10: Convert date_added to Proper Date Format
df['date_added'] = pd.to_datetime(df['date_added'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8794 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8794 non-null   object
 1   type          8794 non-null   object
 2   title         8794 non-null   object
 3   director      8794 non-null   object
 4   cast          8794 non-null   object
 5   country       8794 non-null   object
 6   date_added    8794 non-null   datetime64[ns]
 7   release_year  8794 non-null   int64
 8   rating        8794 non-null   object
 9   duration      8794 non-null   object
 10  listed_in     8794 non-null   object
 11  description   8794 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 893.1+ KB

In [46]:
# STEP 11: Create Separate Year & Month
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8794 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8794 non-null   object
 1   type          8794 non-null   object
 2   title         8794 non-null   object
 3   director      8794 non-null   object
 4   cast          8794 non-null   object
 5   country       8794 non-null   object
 6   date_added    8794 non-null   datetime64[ns]
 7   release_year  8794 non-null   int64
 8   rating        8794 non-null   object
 9   duration      8794 non-null   object
 10  listed_in     8794 non-null   object
 11  description   8794 non-null   object
 12  year_added    8794 non-null   int32
 13  month_added   8794 non-null   int32
dtypes: datetime64[ns](1), int32(2), int64(1), object(10)
memory usage: 961.8+ KB

In [48]:
# STEP 12: Clean the duration Column
# Extract number
df['duration_number'] = df['duration'].str.extract(r'(\d+)').astype(int)

# Create structured columns
df['duration_minutes'] = df.apply(
    lambda x: x['duration_number'] if x['type'] == 'Movie' else 0,
    axis=1
)

df['duration_seasons'] = df.apply(
    lambda x: x['duration_number'] if x['type'] == 'TV Show' else 0,
    axis=1
)

# Drop temporary columns
df = df.drop(columns=['duration', 'duration_number'])

In [49]:
df.info()
df.isnull().sum()
df.shape

<class 'pandas.core.frame.DataFrame'>
Index: 8794 entries, 0 to 8806
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   show_id           8794 non-null   object
 1   type              8794 non-null   object
 2   title             8794 non-null   object
 3   director          8794 non-null   object
 4   cast              8794 non-null   object
 5   country           8794 non-null   object
 6   date_added        8794 non-null   datetime64[ns]
 7   release_year      8794 non-null   int64
 8   rating            8794 non-null   object
 9   listed_in         8794 non-null   object
 10  description       8794 non-null   object
 11  year_added        8794 non-null   int32
 12  month_added       8794 non-null   int32
 13  duration_minutes  8794 non-null   int64
 14  duration_seasons  8794 non-null   int64
dtypes: datetime64[ns](1), int32(2), int64(3), object(9)
memory usage: 1.0+ MB

(8794, 15)

In [50]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,year_added,month_added,duration_minutes,duration_seasons
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Available,United States,2021-09-25,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",2021,9,90,0
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,0,2
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,0,1
3,s4,TV Show,Jailbirds New Orleans,Unknown,Not Available,Unknown,2021-09-24,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9,0,1
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9,0,2
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",Unknown,2021-09-24,2021,TV-MA,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...,2021,9,0,1
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",Unknown,2021-09-24,2021,PG,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,2021,9,91,0
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021,9,125,0
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021,9,0,9
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2021,9,104,0

In [51]:
df.to_csv("netflix_cleaned.csv", index=False)

In [52]:
import os
os.listdir()

['.config',
 'archive (3).zip',
 'netflix_titles.csv.csv',
 'netflix_cleaned.csv',
 'sample_data']

In [53]:
from google.colab import files
files.download("netflix_cleaned.csv")